"use client";

import Link from "next/link";
import { ArrowLeft, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { demoConfig } from "@/config/paired-testing-demo.config";
import { protocolFixture, reportManifestFixture } from "@/data/paired-testing-demo.fixtures";
import { calculateDashboardMetrics } from "@/lib/calculations/dashboard-metrics";
import { formatCurrency } from "@/lib/formatting/currency";
import { formatDemoDate, formatDemoDateTime } from "@/lib/formatting/date-time";
import { useDemoStore } from "@/store/paired-testing-demo.store";

export function PrintReportClient() {
  const pairs = useDemoStore((state) => state.pairs);
  const submissions = useDemoStore((state) => state.submissions);
  const evidence = useDemoStore((state) => state.evidence);
  const metrics = calculateDashboardMetrics(pairs, demoConfig.study.targetPairCount);
  const featured = pairs.find((pair) => pair.id === "PAIR-008")!;
  const featuredA = submissions.find((item) => item.id === featured.testerASubmissionId)!;
  const featuredB = submissions.find((item) => item.id === featured.testerBSubmissionId)!;
  const included = pairs.filter((pair) => pair.expertReviewStatus === "accepted");
  const excluded = pairs.filter((pair) => pair.expertReviewStatus === "rejected" || ["invalid", "incomplete"].includes(pair.overallValidationStatus));
  return (
    <article className="mx-auto max-w-[8.5in] bg-white p-6 text-[#181b19] shadow-2xl print:max-w-none print:p-0 print:shadow-none">
      <div className="no-print mb-5 flex items-center justify-between rounded-md bg-[#07100d] p-3 text-white"><Button asChild variant="ghost"><Link href="/paired-testing-demo/reports"><ArrowLeft className="size-4" />Reports</Link></Button><Button onClick={() => window.print()}><Printer className="size-4" />Print / Save PDF</Button></div>
      <header className="border-b-2 border-[#17251f] pb-8 pt-8">
        <div className="flex items-start justify-between gap-8"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#587065]">DoGoodie · Preparation prototype</p><h1 className="mt-4 text-3xl font-semibold tracking-tight">{demoConfig.study.name}</h1><p className="mt-2 text-sm text-[#587065]">Study summary & expert review package preview</p></div><div className="text-right"><p className="mono text-sm font-semibold">{reportManifestFixture.packageId}</p><p className="mono mt-1 text-[10px] text-[#587065]">{demoConfig.study.id} · {demoConfig.study.protocolVersion}</p><p className="mt-3 inline-block border border-[#17251f] px-2 py-1 text-[9px] font-bold uppercase tracking-wider">Synthetic demonstration data</p></div></div>
      </header>
      <ReportSection title="Prototype disclaimer"><p className="leading-6">{demoConfig.disclaimer}</p></ReportSection>
      <ReportSection title="1. Executive demonstration summary"><p className="leading-6">This front-end prototype illustrates a protocol-led workspace for paired controlled pricing studies. It organizes synthetic tester assignments, validates configured technical controls, links evidence metadata, records expert review decisions, and prepares descriptive exports. It does not establish discrimination, causation, legal liability, admissibility, or scientific validity.</p><div className="mt-5 grid grid-cols-4 gap-2">{[["Submitted pairs", pairs.length], ["Technically valid", metrics.validPairs], ["Accepted", metrics.acceptedPairs], ["Evidence complete", `${metrics.evidenceCompleteRate.toFixed(1)}%`]].map(([label, value]) => <div key={label} className="print-card border border-[#b9c1bd] p-3"><p className="text-[8px] font-bold uppercase tracking-wider text-[#587065]">{label}</p><p className="numeric mt-2 text-xl font-semibold">{value}</p></div>)}</div></ReportSection>
      <ReportSection title="2. Study & protocol metadata"><dl className="grid grid-cols-2 gap-x-10 gap-y-2">{[["Study ID", demoConfig.study.id], ["Study status", demoConfig.study.status], ["Platform", demoConfig.study.platform], ["Ride tier", demoConfig.study.rideTier], ["Origin", demoConfig.study.pickup], ["Destination", demoConfig.study.destination], ["Isolated variable", demoConfig.study.isolatedVariable], ["Protocol version", protocolFixture.version], ["Testing period", `${formatDemoDate(demoConfig.study.testingStart)}–${formatDemoDate(demoConfig.study.testingEnd)}`], ["Display timezone", demoConfig.study.timezone]].map(([label, value]) => <div key={label} className="border-b border-[#d8ddda] py-1.5"><dt className="text-[8px] font-bold uppercase tracking-wider text-[#587065]">{label}</dt><dd className="mono mt-1 text-[9px]">{value}</dd></div>)}</dl><p className="mt-4 text-[9px] leading-5 text-[#587065]">Preliminary thresholds: timestamp ≤5 seconds pass, &gt;5–10 warning, &gt;10 fail; GPS ≤5 feet pass, &gt;5–15 warning, &gt;15 fail. Exact matching required for platform, pickup, destination, ride tier, and currency.</p></ReportSection>
      <ReportSection title="3. Descriptive study metrics"><div className="grid grid-cols-3 gap-3">{[["Average observed variance", `${metrics.averageObservedVariance.toFixed(2)}%`], ["Median observed variance", `${metrics.medianObservedVariance.toFixed(2)}%`], ["Largest observed variance", `${metrics.largestObservedVariance.toFixed(2)}%`], ["Validation rate", `${metrics.validationRate.toFixed(1)}%`], ["Acceptance rate", `${metrics.acceptanceRate.toFixed(1)}%`], ["Completion vs target", `${metrics.completionPercentage.toFixed(1)}%`]].map(([label, value]) => <div key={label} className="print-card border border-[#b9c1bd] p-3"><p className="text-[8px] uppercase tracking-wider text-[#587065]">{label}</p><p className="numeric mt-1 text-base font-semibold">{value}</p></div>)}</div></ReportSection>
      <ReportSection title="4. Included pair table"><PairReportTable pairs={included} submissions={submissions} /></ReportSection>
      <ReportSection title="5. Excluded & incomplete pair table"><PairReportTable pairs={excluded} submissions={submissions} /></ReportSection>
      <ReportSection title="6. Featured matched-pair comparison"><div className="print-card border border-[#17251f] p-4"><div className="flex justify-between"><div><p className="mono font-semibold">{featured.id}</p><p className="mt-1 text-[9px] text-[#587065]">{featuredA.testerAlias} vs {featuredB.testerAlias}</p></div><p className="numeric text-xl font-semibold">{formatCurrency(featured.absolutePriceDifference)} / {featured.percentagePriceDifference.toFixed(2)}%</p></div><div className="mt-4 grid grid-cols-4 gap-2">{[["Tester A quote", formatCurrency(featuredA.displayedPrice)], ["Tester B quote", formatCurrency(featuredB.displayedPrice)], ["Timestamp gap", `${featured.timestampDifferenceSeconds.toFixed(1)}s`], ["GPS distance", `${featured.gpsDistanceFeet.toFixed(1)}ft`]].map(([label, value]) => <div key={label}><p className="text-[8px] uppercase text-[#587065]">{label}</p><p className="numeric mt-1 font-semibold">{value}</p></div>)}</div><p className="mt-4 border-t border-[#d8ddda] pt-3 text-[9px] leading-5 text-[#587065]">{demoConfig.interpretationNote}</p></div></ReportSection>
      <ReportSection title="7. Evidence inventory & reviewer summary"><p>{evidence.length} synthetic evidence metadata records are listed in this package preview. {pairs.filter((pair) => pair.evidenceStatus === "missing").length} pair is marked with missing evidence. Reviewer decisions: {metrics.acceptedPairs} accepted, {metrics.flaggedPairs} flagged, {metrics.rejectedPairs} rejected, and {metrics.pendingReviewPairs} pending.</p></ReportSection>
      <ReportSection title="8. Methodological limitations"><ul className="list-disc space-y-1 pl-5 text-[9px] leading-5 text-[#587065]"><li>All records, identities, evidence labels, routes, and results are synthetic.</li><li>Thresholds and controls have not been validated by qualified experts.</li><li>Descriptive variance does not establish statistical significance, causation, discrimination, or liability.</li><li>No production authentication, storage, chain of custody, cryptographic signing, or external integrations are implemented.</li></ul></ReportSection>
      <ReportSection title="9. Package manifest"><dl className="grid grid-cols-2 gap-2 text-[9px]">{[["Package ID", reportManifestFixture.packageId], ["Study ID", demoConfig.study.id], ["Generated timestamp", formatDemoDateTime(reportManifestFixture.generatedAt)], ["Protocol version", protocolFixture.version], ["Included pair count", String(included.length)], ["Excluded pair count", String(excluded.length)], ["Evidence record count", String(evidence.length)], ["Default print format", demoConfig.reports.printFormat]].map(([label, value]) => <div key={label} className="flex justify-between border-b border-[#d8ddda] py-1"><dt className="text-[#587065]">{label}</dt><dd className="mono">{value}</dd></div>)}</dl></ReportSection>
      <footer className="mt-10 flex justify-between border-t border-[#17251f] pt-3 text-[8px] uppercase tracking-wider text-[#587065]"><span>Preparation prototype · Synthetic demonstration data</span><span>{demoConfig.study.id} · {reportManifestFixture.packageId}</span></footer>
    </article>
  );
}

function ReportSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="print-card mt-8 break-inside-avoid"><h2 className="mb-3 border-b border-[#89978f] pb-2 text-sm font-semibold">{title}</h2><div className="text-[10px]">{children}</div></section>; }
function PairReportTable({ pairs, submissions }: { pairs: ReturnType<typeof useDemoStore.getState>["pairs"]; submissions: ReturnType<typeof useDemoStore.getState>["submissions"] }) { return <table className="w-full text-[8px]"><thead><tr className="bg-[#eef1ef]"><th className="border border-[#b9c1bd] p-1.5 text-left">Pair</th><th className="border border-[#b9c1bd] p-1.5 text-right">Price A</th><th className="border border-[#b9c1bd] p-1.5 text-right">Price B</th><th className="border border-[#b9c1bd] p-1.5 text-right">Variance</th><th className="border border-[#b9c1bd] p-1.5 text-left">Technical</th><th className="border border-[#b9c1bd] p-1.5 text-left">Review</th></tr></thead><tbody>{pairs.map((pair) => { const a = submissions.find((item) => item.id === pair.testerASubmissionId); const b = submissions.find((item) => item.id === pair.testerBSubmissionId); return <tr key={pair.id}><td className="mono border border-[#b9c1bd] p-1.5">{pair.id}</td><td className="numeric border border-[#b9c1bd] p-1.5 text-right">{a ? formatCurrency(a.displayedPrice) : "—"}</td><td className="numeric border border-[#b9c1bd] p-1.5 text-right">{b ? formatCurrency(b.displayedPrice) : "—"}</td><td className="numeric border border-[#b9c1bd] p-1.5 text-right">{pair.percentagePriceDifference.toFixed(2)}%</td><td className="border border-[#b9c1bd] p-1.5">{pair.overallValidationStatus}</td><td className="border border-[#b9c1bd] p-1.5">{pair.expertReviewStatus}</td></tr>; })}</tbody></table>; }

