import type { NavigationItem, Role } from "@/types/paired-testing-demo.types";

export const demoConfig = {
  product: {
    name: "DoGoodie Paired Testing Lab",
    shortName: "Paired Testing Lab",
    subtitle: "Controlled pricing-study operations & expert review",
    description: "A structured workspace for protocol-led paired testing, technical conformity review, and evidence organization.",
    badge: "Internal pilot",
    version: "v0.2",
  },
  disclaimer: "Prototype demonstration using synthetic data. Validation rules, evidence requirements, statistical thresholds, and legal methodology are preliminary and require review by qualified legal, statistical, and forensic experts.",
  shortDisclaimer: "Synthetic demonstration data",
  interpretationNote: "A pricing difference alone does not establish unlawful discrimination. The result must be interpreted in the context of the approved study methodology, repeated observations, statistical analysis, alternative explanations, and applicable law.",
  study: {
    id: "DG-PT-001",
    name: "Manhattan to JFK Paired Pricing Study",
    status: "Active Demonstration",
    studyType: "Same-platform paired pricing comparison",
    location: "New York City",
    pickup: "Midtown Manhattan hotel corridor",
    destination: "JFK Airport Terminal 4",
    platform: "RideApp A",
    platformAliases: ["RideApp A", "RideApp B"],
    rideTier: "Standard Ride",
    currency: "USD",
    timezone: "America/New_York",
    testingStart: "2026-05-12T04:00:00.000Z",
    testingEnd: "2026-05-26T03:59:59.000Z",
    targetPairCount: 100,
    isolatedVariable: "Membership status",
    protocolVersion: "v1.2",
  },
  thresholds: {
    timestamp: { pass: 5, warningMax: 10, unit: "seconds" },
    gps: { pass: 5, warningMax: 15, unit: "feet" },
  },
  rules: {
    exactMatch: ["Platform", "Pickup", "Destination", "Ride tier", "Currency"],
    sameOsFamily: true,
    sameAppVersion: true,
    sameNetworkCategory: false,
    requiredScreenshot: true,
    requiredScreenRecording: true,
  },
  requiredEvidence: ["Quote screenshot", "Screen recording", "Metadata record"],
  roles: {
    coordinator: "Test Coordinator",
    tester: "Tester",
    expert_reviewer: "Expert Reviewer",
    law_firm_viewer: "Law-Firm Viewer",
  } satisfies Record<Role, string>,
  navigation: [
    { label: "Overview", href: "/", icon: "Home" },
    { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
    { label: "Protocol", href: "/protocol", icon: "ClipboardCheck" },
    { label: "Assignments", href: "/assignments", icon: "Users" },
    { label: "Matched Pairs", href: "/pairs", icon: "Columns2" },
    { label: "Evidence", href: "/evidence", icon: "FileArchive" },
    { label: "Activity Log", href: "/audit", icon: "History" },
    { label: "Reports", href: "/reports", icon: "FileText" },
  ] satisfies NavigationItem[],
  reports: {
    titles: ["Study Summary Report", "Protocol Summary", "Accepted Pair Table", "Excluded Pair Table", "Evidence Inventory", "Reviewer Notes"],
    packageId: "PKG-001",
    filenames: {
      pairs: "dg-pt-001-synthetic-pairs.csv",
      acceptedPairs: "dg-pt-001-accepted-pairs.csv",
      excludedPairs: "dg-pt-001-excluded-pairs.csv",
      evidence: "dg-pt-001-evidence-inventory.csv",
      audit: "dg-pt-001-activity-log.csv",
      manifest: "dg-pt-001-package-manifest.json",
      protocol: "dg-pt-001-protocol-summary.txt",
    },
    printFormat: "Letter",
  },
  brand: {
    background: "#07100D", surface: "#0D1814", secondarySurface: "#111F19",
    border: "#26372F", text: "#F5F7F6", muted: "#A9B8B0", lime: "#B7FF3C",
  },
  messages: {
    expertReview: "Expert review required",
    emptyPairs: "No matched pairs meet the selected criteria.",
    localFiles: "Files selected in this demonstration remain local to your browser.",
  },
} as const;

